services:
  ros_jazzy_sim:
    image: ros-jazzy-simulation         # o usa "build: ." si quieres construir local
    container_name: ros_jazzy_sim
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - __NV_PRIME_RENDER_OFFLOAD=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:ro
      - ${HOME}/docker/simulation_qdp/ros2_ws:/home/dev/ros2_ws
    ipc: host
    stdin_open: true
    tty: true
    restart: "no"

    # GPUs en Compose (forma soportada):
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


# docker-compose up