version: "3.9"

services:
  ros_jazzy:
    container_name: quadruped-project
    build:
      context: .
      dockerfile: Dockerfile
    ipc: host
    stdin_open: true
    tty: true
    restart: "no"
    environment:
      DISPLAY: :1
      QT_X11_NO_MITSHM: "1"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: graphics,utility,compute
      __GLX_VENDOR_LIBRARY_NAME: nvidia
      __NV_PRIME_RENDER_OFFLOAD: "1"
      XAUTHORITY: /tmp/.docker.xauth
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:ro
      - ../Quadruped-Project:/workspace/Quadruped-Project:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: -1
              capabilities: [gpu]
